document.addEventListener("DOMContentLoaded",()=>{const contenedor=document.getElementById("agenda");if(!contenedor||!CONFIG.agenda)return;const DIAS=["domingo","lunes","martes","miércoles","jueves","viernes","sábado"];const MESES=["enero","febrero","marzo","abril","mayo","junio","julio","agosto","septiembre","octubre","noviembre","diciembre"];const SEMANAS_MAX_VISITANTE=3;const SEMANAS_MAX_ADMIN=52;const limiteSemanas=()=>esAdmin?SEMANAS_MAX_ADMIN:SEMANAS_MAX_VISITANTE;let semanaOffset=0;let esAdmin=false;let bloqueos=new Set(CONFIG.agenda.bloqueos||[]);let vacaciones=new Set(CONFIG.agenda.vacaciones||[]);let seleccionado=null;let notas={};try{notas=JSON.parse(localStorage.getItem("notasPacientes")||"{}");}catch(e){notas={};}
const guardarNotas=()=>{try{localStorage.setItem("notasPacientes",JSON.stringify(notas));}catch(e){}};const pad=(n)=>String(n).padStart(2,"0");const claveDia=(d)=>d.getFullYear()+"-"+pad(d.getMonth()+1)+"-"+pad(d.getDate());const claveSlot=(d,h)=>claveDia(d)+"T"+pad(h)+":00";function lunesDe(offsetSemanas){const hoy=new Date();const d=new Date(hoy.getFullYear(),hoy.getMonth(),hoy.getDate());const desfase=(d.getDay()+6)%7;d.setDate(d.getDate()-desfase+offsetSemanas*7);return d;}
function slotsDelDia(fecha){const h=CONFIG.agenda.horarios[String(fecha.getDay())];if(!h)return[];const slots=[];for(let hora=h[0];hora<h[1];hora+=CONFIG.agenda.duracionMin/60){slots.push(claveSlot(fecha,hora));}
return slots;}
const esPasado=(clave)=>{const ahora=new Date();const actual=ahora.getFullYear()+"-"+pad(ahora.getMonth()+1)+"-"+
pad(ahora.getDate())+"T"+pad(ahora.getHours())+":"+pad(ahora.getMinutes());return clave<=actual;};function render(){const lunes=lunesDe(semanaOffset);const domingo=new Date(lunes);domingo.setDate(lunes.getDate()+6);let html='<div class="agenda-cabecera">';html+='<button type="button" class="agenda-nav" id="agendaPrev" '+
(semanaOffset===0?"disabled":"")+'>← Semana anterior</button>';html+='<span class="agenda-titulo">Semana del '+lunes.getDate()+" de "+MESES[lunes.getMonth()]+" al "+domingo.getDate()+" de "+MESES[domingo.getMonth()]+"</span>";html+='<button type="button" class="agenda-nav" id="agendaNext" '+
(semanaOffset>=limiteSemanas()-1?"disabled":"")+'>Semana siguiente →</button>';html+="</div>";html+='<div class="agenda-semana">';for(let i=0;i<7;i++){const dia=new Date(lunes);dia.setDate(lunes.getDate()+i);const cerrado=vacaciones.has(claveDia(dia));html+='<div class="agenda-dia">';html+='<div class="agenda-dia-nombre">'+DIAS[dia.getDay()]+'</div>';html+='<div class="agenda-dia-fecha">'+dia.getDate()+" "+MESES[dia.getMonth()].slice(0,3)+'</div>';if(cerrado){html+='<div class="agenda-cerrado">cerrado</div>';}else{const slots=slotsDelDia(dia);if(slots.length===0){html+='<div class="agenda-cerrado">cerrado</div>';}
slots.forEach((clave)=>{const hora=clave.slice(11);const ocupado=bloqueos.has(clave);const pasado=esPasado(clave);let clase="agenda-slot";if(ocupado)clase+=" ocupado";if(pasado)clase+=" pasado";if(seleccionado===clave)clase+=" elegido";html+='<button type="button" class="'+clase+'" data-slot="'+clave+'"'+
((pasado||(ocupado&&!esAdmin))?" disabled":"")+'>'+
hora+(ocupado&&esAdmin?" ✕":"")+"</button>";if(esAdmin){html+='<button type="button" class="agenda-nota-btn" data-nota="'+clave+'" title="Nota de paciente">'+(notas[clave]?"📝":"✎")+"</button>";}});}
html+="</div>";}
html+="</div>";if(esAdmin){html+='<div class="agenda-admin">'+"<strong>Modo gestión de Ángela</strong> · Pulsa un hueco para bloquearlo o liberarlo. El ✎ abre sus notas. "+'<button type="button" id="agendaCopiar">Copiar configuración</button>'+'<button type="button" id="agendaAjustes">⚙ Ajustes</button>'+'<button type="button" id="agendaFactura">🧾 Nueva factura</button>'+'<span id="agendaAdminAviso"></span></div>'+renderNotas();}else{html+='<p class="agenda-nota">Pulsa un hueco libre y se rellena el formulario de abajo.</p>';}
contenedor.innerHTML=html;document.getElementById("agendaPrev").addEventListener("click",()=>{if(semanaOffset>0){semanaOffset--;render();}});document.getElementById("agendaNext").addEventListener("click",()=>{if(semanaOffset<limiteSemanas()-1){semanaOffset++;render();}});contenedor.querySelectorAll(".agenda-slot").forEach((btn)=>{btn.addEventListener("click",()=>{const clave=btn.dataset.slot;if(esAdmin){if(bloqueos.has(clave))bloqueos.delete(clave);else bloqueos.add(clave);render();}else{seleccionado=clave;const campo=document.getElementById("citaFecha");if(campo){campo.value=clave;campo.scrollIntoView({behavior:"smooth",block:"center"});campo.focus();}
render();}});});contenedor.querySelectorAll("[data-nota]").forEach((b)=>{b.addEventListener("click",(e)=>{e.stopPropagation();abrirNota(b.dataset.nota);});});
contenedor.querySelectorAll("[data-editarnota]").forEach((el)=>{el.addEventListener("click",()=>abrirNota(el.dataset.editarnota));});
const btnExp=document.getElementById("notasExportar");if(btnExp){btnExp.addEventListener("click",()=>{const claves=Object.keys(notas).sort();let txt="NOTAS DE PACIENTES (exportado "+new Date().toLocaleString("es-ES")+")\n\n";claves.forEach((c)=>{const n=notas[c];txt+="■ "+fechaBonitaClave(c)+" — "+(n.titulo||"Sin título")+"\n"+(n.descripcion?"  Motivo: "+n.descripcion+"\n":"")+(n.notas?"  Notas: "+n.notas+"\n":"")+"\n";});navigator.clipboard.writeText(txt).then(()=>{btnExp.textContent="¡Copiado!";setTimeout(()=>{btnExp.textContent="Exportar notas";},2000);});});}
const btnAj=document.getElementById("agendaAjustes");if(btnAj)btnAj.addEventListener("click",abrirAjustes);
const btnFa=document.getElementById("agendaFactura");if(btnFa)btnFa.addEventListener("click",abrirFactura);
const btnCopiar=document.getElementById("agendaCopiar");if(btnCopiar){btnCopiar.addEventListener("click",()=>{const texto="    agenda: {\n"+"        duracionMin: "+CONFIG.agenda.duracionMin+",\n"+"        horarios: "+JSON.stringify(CONFIG.agenda.horarios)+",\n"+"        bloqueos: "+JSON.stringify([...bloqueos].sort())+",\n"+"        vacaciones: "+JSON.stringify([...vacaciones].sort())+"\n"+"    },";navigator.clipboard.writeText(texto).then(()=>{document.getElementById("agendaAdminAviso").textContent=" ¡Copiado! Ahora pégalo en js/config.js (en GitHub: entra al archivo, lápiz de editar, sustituye el bloque agenda y guarda).";});});}}
function fechaBonitaClave(clave){const y=+clave.slice(0,4),m=+clave.slice(5,7)-1,d=+clave.slice(8,10);const f=new Date(y,m,d);return DIAS[f.getDay()]+" "+d+" de "+MESES[m]+" · "+clave.slice(11);}
function renderNotas(){const claves=Object.keys(notas).sort().reverse();let h='<div class="panel-notas"><div class="panel-notas-cab"><strong>📋 Notas de pacientes</strong><span class="panel-notas-acc"><button type="button" id="notasExportar">Exportar notas</button></span></div>'+'<p class="panel-notas-aviso">Privado: estas notas se guardan <strong>solo en este navegador de este dispositivo</strong>. No se suben a GitHub ni aparecen en la web. Usa alias o iniciales, nunca apellidos. Si limpias el navegador se borran: exporta antes.</p>';if(claves.length===0){h+='<p class="panel-notas-vacio">Todavía no hay notas. Pulsa el ✎ de cualquier hueco para anotar la primera.</p>';}else{claves.forEach((c)=>{const n=notas[c];h+='<div class="nota-item" data-editarnota="'+c+'"><div class="nota-item-cab"><strong>'+(n.titulo||"Sin título")+'</strong><span>'+fechaBonitaClave(c)+"</span></div>"+(n.descripcion?'<p class="nota-desc">'+n.descripcion+"</p>":"")+(n.notas?'<p class="nota-priv">'+n.notas+"</p>":"")+"</div>";});}
h+="</div>";return h;}
function abrirNota(clave){const n=notas[clave]||{};document.getElementById("notaSlot").value=clave;document.getElementById("notaFechaTxt").textContent=fechaBonitaClave(clave);document.getElementById("notaTitulo").value=n.titulo||"";document.getElementById("notaDescripcion").value=n.descripcion||"";document.getElementById("notaNotas").value=n.notas||"";document.getElementById("notaEliminar").style.display=notas[clave]?"":"none";document.getElementById("notaModal").classList.add("visible");setTimeout(()=>document.getElementById("notaTitulo").focus(),250);}
function cerrarNota(){document.getElementById("notaModal").classList.remove("visible");}
function guardarNota(){const clave=document.getElementById("notaSlot").value;const t=document.getElementById("notaTitulo").value.trim();const d=document.getElementById("notaDescripcion").value.trim();const tx=document.getElementById("notaNotas").value.trim();if(!t&&!d&&!tx){delete notas[clave];}else{notas[clave]={titulo:t,descripcion:d,notas:tx,actualizada:new Date().toISOString()};}
guardarNotas();cerrarNota();render();}
function borrarNota(){const clave=document.getElementById("notaSlot").value;delete notas[clave];guardarNotas();cerrarNota();render();}
document.getElementById("notaGuardar").addEventListener("click",guardarNota);document.getElementById("notaEliminar").addEventListener("click",borrarNota);document.getElementById("notaCancelar").addEventListener("click",cerrarNota);document.getElementById("notaModal").addEventListener("click",(e)=>{if(e.target===document.getElementById("notaModal"))cerrarNota();});
/* ===== AJUSTES (edita la web sin tocar código) ===== */
function abrirAjustes(){document.getElementById("ajPresencial").checked=!!CONFIG.presencialActivo;document.getElementById("ajTIndividual").value=CONFIG.tarifas.individual.precio;document.getElementById("ajTMensual").value=CONFIG.tarifas.mensual.precio;document.getElementById("ajTOnline").value=CONFIG.tarifas.online.precio;document.getElementById("ajTPareja").value=CONFIG.tarifas.pareja.precio;document.getElementById("ajGarantia").value=CONFIG.garantiaImporte;document.getElementById("ajBizum").value=CONFIG.bizumNumero;document.getElementById("ajEmail").value=CONFIG.email;document.getElementById("ajJitsi").value=CONFIG.enlaceVideollamada||"";document.getElementById("ajAviso").textContent="";document.getElementById("ajustesModal").classList.add("visible");}
function generarConfig(){const t='const CONFIG = {\n    nombre:      '+JSON.stringify(CONFIG.nombre)+',\n    numColegiada: '+JSON.stringify(CONFIG.numColegiada)+',\n    telefono:    '+JSON.stringify(CONFIG.telefono)+',\n    telefonoBonito: '+JSON.stringify(CONFIG.telefonoBonito)+',\n    email:       '+JSON.stringify(document.getElementById("ajEmail").value.trim())+',\n    ciudad:      '+JSON.stringify(CONFIG.ciudad)+',\n\n    presencialActivo: '+document.getElementById("ajPresencial").checked+',\n\n    fiscal: '+JSON.stringify(CONFIG.fiscal)+',\n\n    garantiaImporte: '+JSON.stringify(document.getElementById("ajGarantia").value.trim())+',\n    bizumNumero: '+JSON.stringify(document.getElementById("ajBizum").value.trim())+',\n    enlaceVideollamada: '+JSON.stringify(document.getElementById("ajJitsi").value.trim())+',\n    formspreeId: '+JSON.stringify(CONFIG.formspreeId||"")+',\n\n    adminHash: '+JSON.stringify(CONFIG.adminHash)+',\n\n    tarifas: {\n        individual: { precio: '+JSON.stringify(document.getElementById("ajTIndividual").value.trim())+', nota: '+JSON.stringify(CONFIG.tarifas.individual.nota)+' },\n        mensual:    { precio: '+JSON.stringify(document.getElementById("ajTMensual").value.trim())+', nota: '+JSON.stringify(CONFIG.tarifas.mensual.nota)+' },\n        online:     { precio: '+JSON.stringify(document.getElementById("ajTOnline").value.trim())+', nota: '+JSON.stringify(CONFIG.tarifas.online.nota)+' },\n        pareja:     { precio: '+JSON.stringify(document.getElementById("ajTPareja").value.trim())+', nota: '+JSON.stringify(CONFIG.tarifas.pareja.nota)+' }\n    },\n\n    agenda: {\n        duracionMin: '+CONFIG.agenda.duracionMin+',\n        horarios: '+JSON.stringify(CONFIG.agenda.horarios)+',\n        bloqueos: '+JSON.stringify([...bloqueos].sort())+',\n        vacaciones: '+JSON.stringify([...vacaciones].sort())+'\n    }\n};\n';navigator.clipboard.writeText(t).then(()=>{document.getElementById("ajAviso").style.color="#2e7d5b";document.getElementById("ajAviso").textContent="¡Copiado! En GitHub: abre js/config.js → lápiz → borra todo → pega → Commit changes. En 1-2 minutos la web pública se actualiza.";});}
document.getElementById("ajGenerar").addEventListener("click",generarConfig);document.getElementById("ajCancelar").addEventListener("click",()=>document.getElementById("ajustesModal").classList.remove("visible"));

/* ===== FACTURAS SIMPLES (PDF vía imprimir) ===== */
function numeroFactura(){const anio=new Date().getFullYear();let n=1;try{n=parseInt(localStorage.getItem("facturaNum"+anio)||"0",10)+1;}catch(e){}try{localStorage.setItem("facturaNum"+anio,String(n));}catch(e){}return anio+"-"+String(n).padStart(3,"0");}
function abrirFactura(){document.getElementById("faFecha").value=new Date().toISOString().slice(0,10);document.getElementById("facturaModal").classList.add("visible");setTimeout(()=>document.getElementById("faCliente").focus(),250);}
function generarFactura(){const num=numeroFactura();const cliente=document.getElementById("faCliente").value.trim()||"Cliente";const nifCli=document.getElementById("faClienteNif").value.trim();const concepto=document.getElementById("faConcepto").value;const importe=parseFloat(document.getElementById("faImporte").value.replace(",","."))||0;const fecha=document.getElementById("faFecha").value;const f=CONFIG.fiscal||{};const fechaBonita=fecha?new Date(fecha+"T00:00").toLocaleDateString("es-ES",{day:"numeric",month:"long",year:"numeric"}):"";const iva="Exenta de IVA (art. 20.uno.3º Ley 37/1992, servicios sanitarios)";const w=window.open("","_blank");w.document.write("<!DOCTYPE html><html lang='es'><head><meta charset='utf-8'><title>Factura "+num+"</title><style>body{font-family:-apple-system,'Segoe UI',sans-serif;max-width:700px;margin:40px auto;padding:0 24px;color:#2c3e50;line-height:1.5}h1{font-size:1.4rem;color:#2f6b7c;margin-bottom:4px}.sub{color:#6b7c8a;font-size:.85rem;margin-bottom:28px}.bloque{margin-bottom:18px;font-size:.92rem}.bloque strong{color:#2f6b7c}table{width:100%;border-collapse:collapse;margin:22px 0}th{background:#eef6f9;text-align:left;padding:8px 10px;font-size:.8rem;color:#2f6b7c;text-transform:uppercase}td{padding:10px;border-bottom:1px solid #d4e5ec;font-size:.92rem}.total td{font-weight:700;font-size:1.05rem;border-top:2px solid #5a9caf}.pie{margin-top:34px;font-size:.78rem;color:#8fa5b3}@media print{body{margin:0}}</style></head><body><h1>FACTURA "+num+"</h1><p class='sub'>"+fechaBonita+"</p><div class='bloque'><strong>Emite:</strong><br>"+(f.nombre||"")+"<br>NIF: "+(f.nif||"")+"<br>"+(f.direccion||"")+"</div><div class='bloque'><strong>Factura a:</strong><br>"+cliente+(nifCli?"<br>NIF: "+nifCli:"")+"</div><table><tr><th>Concepto</th><th style='text-align:right'>Importe</th></tr><tr><td>"+concepto+" — servicio de psicología sanitaria</td><td style='text-align:right'>"+importe.toFixed(2)+" €</td></tr><tr class='total'><td>TOTAL</td><td style='text-align:right'>"+importe.toFixed(2)+" €</td></tr></table><p class='bloque'>"+iva+".<br>Pago recibido por Bizum.</p><p class='pie'>Documento generado desde el área privada de la consulta. Para cualquier duda sobre esta factura, responde al correo de confirmación de tu cita.</p><script>window.onload=function(){window.print();};<\/script></body></html>");w.document.close();document.getElementById("facturaModal").classList.remove("visible");}
document.getElementById("faGenerar").addEventListener("click",generarFactura);document.getElementById("faCancelar").addEventListener("click",()=>document.getElementById("facturaModal").classList.remove("visible"));

const modal=document.getElementById("loginModal");const campoUsuario=document.getElementById("loginUsuario");const campoPassword=document.getElementById("loginPassword");const errorLogin=document.getElementById("loginError");async function verificarCredenciales(usuario,password){const limpio=usuario.replace(/^@/,"").trim();const cadena="agenda-angela|"+limpio+"|"+password;const datos=new TextEncoder().encode(cadena);const buffer=await crypto.subtle.digest("SHA-256",datos);const hex=[...new Uint8Array(buffer)].map((b)=>b.toString(16).padStart(2,"0")).join("");return hex===CONFIG.adminHash;}
function abrirLogin(){if(esAdmin)return;errorLogin.textContent="";campoUsuario.value="";campoPassword.value="";modal.classList.add("visible");setTimeout(()=>campoUsuario.focus(),250);}
function cerrarLogin(){modal.classList.remove("visible");}
function intentarLogin(){verificarCredenciales(campoUsuario.value,campoPassword.value).then((ok)=>{if(ok){esAdmin=true;cerrarLogin();contenedor.scrollIntoView({behavior:"smooth",block:"start"});render();}else{errorLogin.textContent="Usuario o contraseña incorrectos.";campoPassword.value="";campoPassword.focus();}});}
document.getElementById("btnAcceso").addEventListener("click",abrirLogin);document.getElementById("loginEntrar").addEventListener("click",intentarLogin);document.getElementById("loginCancelar").addEventListener("click",cerrarLogin);campoPassword.addEventListener("keydown",(e)=>{if(e.key==="Enter")intentarLogin();});campoUsuario.addEventListener("keydown",(e)=>{if(e.key==="Enter")campoPassword.focus();});modal.addEventListener("click",(e)=>{if(e.target===modal)cerrarLogin();});document.addEventListener("keydown",(e)=>{if(e.key==="Escape"&&modal.classList.contains("visible"))cerrarLogin();if(e.key==="Escape"){cerrarNota();document.getElementById("ajustesModal").classList.remove("visible");document.getElementById("facturaModal").classList.remove("visible");}if(e.ctrlKey&&e.shiftKey&&(e.key==="A"||e.key==="a")){e.preventDefault();abrirLogin();}});render();});