document.addEventListener("DOMContentLoaded",()=>{const boton=document.getElementById("chatBoton");const panel=document.getElementById("chatPanel");const mensajes=document.getElementById("chatMensajes");const entrada=document.getElementById("chatTexto");const enviar=document.getElementById("chatEnviar");if(!boton||!panel)return;const telBonito=CONFIG.telefonoBonito;const garantia=CONFIG.garantiaImporte||"5€";const enlaceCitas='<a href="#citas" onclick="document.getElementById(\'chatPanel\').classList.remove(\'visible\');document.getElementById(\'chatBoton\').classList.remove(\'abierto\')">la sección de citas</a>';const enlaceTarifas='<a href="#tarifas" onclick="document.getElementById(\'chatPanel\').classList.remove(\'visible\');document.getElementById(\'chatBoton\').classList.remove(\'abierto\')">las tarifas</a>';const CIERRE=" Si te apetece, el mejor paso es pedir cita con ella: hablar con ella por videollamada es donde de verdad se trabaja.";const excusas=["La doctora pasa casi todo el día en consulta con sus pacientes y los huecos vuelan, sobre todo a primera y última hora.","Últimamente tiene la agenda bastante llena: mucha gente empieza terapia en estas fechas y las citas se reservan con días de antelación.","Entre las sesiones presenciales y las online, el calendario se llena rápido. No es que no quiera atenderte, es que físicamente no hay más horas en el día."];let excusaIdx=0;const norm=(t)=>t.toLowerCase().normalize("NFD").replace(/[̀-ͯ]/g,"");function responder(pregunta){const t=norm(pregunta);const personal=["ansiedad","depresion","triste","suicid","autolesion","me siento","estoy mal","tratamiento","terapia para","consejo","que hago con","mi pareja me","no puedo mas","ayudame","medicacion","diagnostico","tengo toc","trauma","duelo","llorar","miedo a"];const crisis=["suicid","hacerme dano","hacerme daño","quitarme la vida","acabar con todo","no quiero vivir","quiero morir","matarme","autolesion"];if(crisis.some(p=>t.includes(p))){return"Siento mucho que estés pasando por esto. Yo soy solo una asistente web y esto es demasiado importante para esperar una cita: llama ahora al 024 (línea de atención a la conducta suicida, gratis, 24 horas) o al 112 si estás en peligro. No estás sol@. Cuando estés a salvo, la doctora estará aquí para acompañarte.";}
if(personal.some(p=>t.includes(p))){return"Eso que me cuentas merece escucharlo bien, y yo soy solo una asistente de la web: no puedo dar consejos ni valorar casos. "+"La doctora sí. Te animo de verdad a que se lo cuentes a ella en una sesión — para eso está. "+"Puedes pedir cita en "+enlaceCitas+" o escribirle al WhatsApp "+telBonito+".";}
if(/\b(hola|buenas|hey|buenos dias|buenas tardes)\b/.test(t)){return"¡Hola! Soy la asistente de la web. Puedo contarte cosas sobre la doctora, las tarifas, cómo pedir cita o cómo funcionan las sesiones online. ¿Qué necesitas?";}
if(t.includes("garantia")||t.includes("fianza")||t.includes("devuelv")||t.includes("cancelar")||t.includes("no puedo ir")){return"Para confirmar la cita se pide una garantía de "+garantia+" por Bizum. No es un pago extra: se descuenta del precio de la sesión. "+"Si avisas con 24 horas, se te devuelve o se traslada la cita, como prefieras. Si no acudes sin avisar, no se devuelve: es la compensación por el hueco perdido. "+"Está todo escrito en las condiciones de reserva del aviso legal.";}
if(t.includes("precio")||t.includes("tarifa")||t.includes("cuesta")||t.includes("cuanto vale")||t.includes("cuanto cuesta")){return"La sesión individual son "+CONFIG.tarifas.individual.precio+", el bono mensual "+CONFIG.tarifas.mensual.precio+" (4 sesiones) y la de pareja "+CONFIG.tarifas.pareja.precio+". Todo está detallado en "+enlaceTarifas+", sin letra pequeña. "+"Para confirmar la cita hay una garantía de "+garantia+" que se descuenta de la sesión.";}
if(t.includes("cita")||t.includes("reserv")||t.includes("agenda")||t.includes("pedir hora")||t.includes("apuntar")){return"Pedir cita es fácil: baja a "+enlaceCitas+", elige un hueco libre en el calendario y envía la solicitud. "+"Ojo: las citas SOLO se piden desde ese calendario online, nunca por llamada ni por WhatsApp (esos canales son solo para dudas). "+"La doctora te confirma por email y te pide una garantía de "+garantia+" por Bizum, que se descuenta de la sesión."+CIERRE;}
if(t.includes("no hay")&&(t.includes("cita")||t.includes("hueco"))||t.includes("lleno")||t.includes("disponib")){const excusa=excusas[excusaIdx%excusas.length];excusaIdx++;return excusa+" Pero tiene un protocolo para estos casos: mándale un mensaje de voz o texto al WhatsApp "+telBonito+" contándole brevemente tu caso, y al cerrar su última consulta del día te responde ella misma con una primera pauta y busca un hueco de emergencia. Sin listas de espera impersonales.";}
if(t.includes("contact")||t.includes("telefono")||t.includes("whatsapp")||t.includes("email")||t.includes("correo")||t.includes("llamar")){return"Puedes escribirle al WhatsApp "+telBonito+", llamar al mismo número o mandar un email a "+CONFIG.email+", pero solo para dudas: las citas no se piden por esos canales, solo desde el calendario online de la web. El formulario de contacto de abajo abre tu propio correo: nada se guarda en la web.";}
if(t.includes("donde")||t.includes("ubicacion")||t.includes("direccion")||t.includes("consulta")||t.includes("sevilla")||t.includes("llegar")){return"Ahora mismo la doctora trabaja online, por videollamada, así que da igual dónde estés: solo necesitas un móvil u ordenador. Ella es de "+CONFIG.ciudad+" y cuando abra consulta presencial se avisará en la web. Los horarios: lunes a viernes de 9:00 a 20:00 y sábados de 10:00 a 14:00.";}
if(t.includes("online")||t.includes("videollamada")||t.includes("presencial")||t.includes("distancia")){return"De momento las sesiones son online, por videollamada, desde donde te venga mejor. Se hacen por Jitsi Meet (meet.jit.si), una plataforma cifrada y de código abierto: cuando la doctora confirme tu cita te envía un enlace único, lo abres en el navegador de tu móvil u ordenador y entras, sin cuenta y sin instalar nada. Y nunca se graba nada sin tu consentimiento expreso."+CIERRE;}
if(t.includes("quien")||t.includes("doctora")||t.includes("psicologa")||t.includes("ella")||t.includes("formacion")||t.includes("colegiada")){return"Es psicóloga sanitaria colegiada (su número está en el pie de la web), con formación en terapia cognitivo-conductual y experiencia con ansiedad, duelo, parejas y procesos de cambio. "+"Lo que más la define: es directa, sin rodeos, y si cree que tu caso necesita a otra persona, te lo dice y te orienta."+CIERRE;}
if(t.includes("test")){return"El test de la web son 10 preguntas de orientación, unos 3 minutos. No es un diagnóstico: es un punto de partida para ver por dónde vas. "+"Ocurre entero en tu navegador y tus respuestas no salen de tu dispositivo. Y si luego pides cita o escribes a la doctora, tu informe viaja contigo en el correo, automáticamente, para que ella ya sepa por dónde empezar.";}
if(t.includes("privacid")||t.includes("datos")||t.includes("cookies")||t.includes("segur")){return"Esta web no guarda nada de ti: sin cookies de seguimiento, sin base de datos, sin estadísticas. El formulario abre tu propio correo y el test ocurre en tu navegador. "+"Y esta conversación conmigo tampoco sale de tu dispositivo. Está todo en la política de privacidad, abajo en el pie.";}
if(t.includes("pago")||t.includes("pagar")||t.includes("bizum")||t.includes("paypal")||t.includes("tarjeta")){return"La garantía de reserva ("+garantia+") y las sesiones se pagan por Bizum al "+(CONFIG.bizumNumero||telBonito)+", directamente a la psicóloga. La web no procesa ni guarda ningún dato de pago.";}
if(t.includes("gracias")){return"¡A ti! Si necesitas algo más sobre la web, aquí estoy. Y recuerda: el paso que de verdad cambia las cosas es pedir cita con la doctora.";}
if(t.includes("adios")||t.includes("hasta luego")||t.includes("chao")){return"¡Hasta pronto! Cuídate. Y si algún día lo necesitas, ya sabes dónde encontrarla.";}
return"Solo sé hablar de la web: quién es la doctora, tarifas, citas, contacto y poco más. Para cualquier cosa personal, lo mejor es hablar con ella directamente."+CIERRE;}
function burbuja(texto,quien){const div=document.createElement("div");div.className="msg "+quien;if(quien==="bot"){div.innerHTML=texto;}else{div.textContent=texto;}
mensajes.appendChild(div);mensajes.scrollTop=mensajes.scrollHeight;}
function enviarMensaje(texto){const limpio=texto.trim();if(!limpio)return;burbuja(limpio,"usuario");entrada.value="";setTimeout(()=>burbuja(responder(limpio),"bot"),450);}
boton.addEventListener("click",()=>{const abierto=panel.classList.toggle("visible");boton.classList.toggle("abierto",abierto);if(abierto)entrada.focus();if(abierto&&mensajes.children.length===0){setTimeout(()=>burbuja("¡Hola! Soy la asistente de la web. Te cuento lo que necesites sobre la doctora, las citas o las tarifas. "+"Eso sí: no doy consejos psicológicos — para eso está ella, que es la profesional.","bot"),350);}});document.addEventListener("keydown",(e)=>{if(e.key==="Escape"&&panel.classList.contains("visible")){panel.classList.remove("visible");boton.classList.remove("abierto");boton.focus();}});enviar.addEventListener("click",()=>enviarMensaje(entrada.value));entrada.addEventListener("keydown",(e)=>{if(e.key==="Enter")enviarMensaje(entrada.value);});document.querySelectorAll(".chat-chips button").forEach(chip=>{chip.addEventListener("click",()=>enviarMensaje(chip.textContent));});});